// export const Main = 'Main'
// export const ThongTinCaNhan = 'ThongTinCaNhan'
const ScreenName = {
  Intro: 'Intro',
  Main: 'Main',
  ThongTinCaNhan: 'ThongTinCaNhan',
  DoiMatKhau: 'DoiMatKhau',
  DynamicFormTest: 'DynamicFormTest',
  QuenMatKhau: 'QuenMatKhau',
  Login: 'Login',
  SeePDF: 'SeePDF',
  TrangChu: 'TrangChu',
  NghienCuuKhoaHoc: 'NghienCuuKhoaHoc',
  KeKhaiGiaiThuong: 'KeKhaiGiaiThuong',
  KeKhaiSachTapChi: 'KeKhaiSachTapChi',
  KeKhaiBaiBaoBaoCao: 'KeKhaiBaiBaoBaoCao',
  TableDetail: 'TableDetail',
  HanhChinh: 'HanhChinh',
  DonTu: 'DonTu',
  DanhSachChucNangDon: 'DanhSachChucNangDon',
  DanhSachDon: 'DanhSachDon',
  ChiTietDon: 'ChiTietDon',
  DanhSachCanBo: 'DanhSachCanBo',
  ChiTietYKien: 'ChiTietYKien',
  HoSoCanBo: 'HoSoCanBo',
  CapQuyetDinh: 'CapQuyetDinh',
  TabMain: 'TabMain',
  ChiTietThongBao: 'ChiTietThongBao',
  ChiTietChuDauTu: 'ChiTietChuDauTu',
  ChiTietGoiThau: 'ChiTietGoiThau',
  WebViewScreen: 'WebViewScreen',
  OhNo: 'OhNo',
  DanhSachGoiThauChuDauTu: 'DanhSachGoiThauChuDauTu',
}
export default ScreenName
